language: rust

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  include:
    - rust: nightly
    - rust: beta
    - rust: stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - cargo test --features="live_tests"
  - cargo test --features="tls"
  - travis-cargo --only stable doc -- --no-deps --features="tls"

sudo: false

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls --no-sudo -- --features="tls live_tests"

env:
  global:
    secure: eSYRUJ2wTq1g6AiPp0zvtxVJFn/3FnrCRAJmGCN1TBYpnl11ZvLZfhUA9IC4S48/YVmdeP1pywpIjY3ZGk7gWuaRLpTrwBxgm01RbOglQS1if6Pryc01FcwCSGb1fJKY4qR0v6iQRb23jaFfSELHfThf4rmG4QiKiNviHJRzb0c=
